--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/diamond-gold/DummyItemsBlocks
build-by-default: true
branches:
- main
projects:
  DummyItemsBlocks:
    path: ""
    icon: icon.gif
    lint:
      phpstan: false
      syntaxError: false
...
